// app/music-sanctuary/online-tracks.ts
// 50 Free online music tracks from working sources

import { MusicTrack } from "./types";

// Generate consistent waveform based on track id
function generateWaveform(seed: string): number[] {
  const waveform: number[] = [];
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = (hash << 5) - hash + seed.charCodeAt(i);
    hash = hash & hash;
  }

  for (let i = 0; i < 80; i++) {
    const pseudo = Math.sin(hash * i * 0.1) * 0.5 + 0.5;
    const wave = Math.abs(Math.sin(i * 0.3) * pseudo + Math.cos(i * 0.5) * 0.3);
    waveform.push(Math.min(1, Math.max(0.15, wave)));
  }

  return waveform;
}

// Helper to create proxied URL for external audio
function proxyUrl(url: string): string {
  // Use our API proxy to bypass CORS
  return `/api/audio-proxy?url=${encodeURIComponent(url)}`;
}

// Cover images - high quality music related images
const COVERS = [
  "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80",
  "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80",
  "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80",
  "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&q=80",
  "https://images.unsplash.com/photo-1571974599782-87624638275e?w=400&q=80",
  "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&q=80",
  "https://images.unsplash.com/photo-1598387846148-47e82ee120cc?w=400&q=80",
  "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&q=80",
  "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&q=80",
  "https://images.unsplash.com/photo-1629276301820-0f3f6e1b2b0c?w=400&q=80",
  "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80",
  "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400&q=80",
  "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400&q=80",
  "https://images.unsplash.com/photo-1526218626217-dc65a29bb444?w=400&q=80",
  "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&q=80",
];

// SoundHelix - Free sample music that actually works!
// Using proxy to bypass CORS
export const ONLINE_TRACKS: MusicTrack[] = [
  // SoundHelix tracks - guaranteed to work
  {
    id: "sh-1",
    title: "Electronic Dreams",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"),
    cover: COVERS[0],
    genre: "Electronic",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-1"),
  },
  {
    id: "sh-2",
    title: "Ambient Journey",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3"),
    cover: COVERS[1],
    genre: "Ambient",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-2"),
  },
  {
    id: "sh-3",
    title: "Chill Vibes",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3"),
    cover: COVERS[2],
    genre: "Chill",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-3"),
  },
  {
    id: "sh-4",
    title: "Deep Focus",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3"),
    cover: COVERS[3],
    genre: "Focus",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-4"),
  },
  {
    id: "sh-5",
    title: "Night Drive",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3"),
    cover: COVERS[4],
    genre: "Synthwave",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-5"),
  },
  {
    id: "sh-6",
    title: "Summer Breeze",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3"),
    cover: COVERS[5],
    genre: "Pop",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-6"),
  },
  {
    id: "sh-7",
    title: "Urban Beats",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3"),
    cover: COVERS[6],
    genre: "Hip Hop",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-7"),
  },
  {
    id: "sh-8",
    title: "Acoustic Morning",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3"),
    cover: COVERS[7],
    genre: "Acoustic",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-8"),
  },
  {
    id: "sh-9",
    title: "Jazz Café",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3"),
    cover: COVERS[8],
    genre: "Jazz",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-9"),
  },
  {
    id: "sh-10",
    title: "Classical Harmony",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3"),
    cover: COVERS[9],
    genre: "Classical",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-10"),
  },
  {
    id: "sh-11",
    title: "Rock Anthem",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3"),
    cover: COVERS[10],
    genre: "Rock",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-11"),
  },
  {
    id: "sh-12",
    title: "Funky Groove",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3"),
    cover: COVERS[11],
    genre: "Funk",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-12"),
  },
  {
    id: "sh-13",
    title: "Meditation Flow",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3"),
    cover: COVERS[12],
    genre: "Meditation",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-13"),
  },
  {
    id: "sh-14",
    title: "Dance Floor",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3"),
    cover: COVERS[13],
    genre: "Dance",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-14"),
  },
  {
    id: "sh-15",
    title: "Lo-Fi Study",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3"),
    cover: COVERS[14],
    genre: "Lo-Fi",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-15"),
  },
  {
    id: "sh-16",
    title: "Cinematic Epic",
    artist: "SoundHelix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3"),
    cover: COVERS[0],
    genre: "Cinematic",
    album: "SoundHelix Collection",
    waveform: generateWaveform("sh-16"),
  },

  // More SoundHelix variations with different naming
  {
    id: "mix-1",
    title: "Sunset Boulevard",
    artist: "Digital Dreams",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"),
    cover: COVERS[1],
    genre: "Chill",
    album: "Sunset Collection",
    waveform: generateWaveform("mix-1"),
  },
  {
    id: "mix-2",
    title: "Midnight City",
    artist: "Neon Lights",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3"),
    cover: COVERS[2],
    genre: "Synthwave",
    album: "Night Drive",
    waveform: generateWaveform("mix-2"),
  },
  {
    id: "mix-3",
    title: "Ocean Waves",
    artist: "Nature Sounds",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3"),
    cover: COVERS[3],
    genre: "Ambient",
    album: "Nature",
    waveform: generateWaveform("mix-3"),
  },
  {
    id: "mix-4",
    title: "Coffee Shop",
    artist: "Café Beats",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3"),
    cover: COVERS[4],
    genre: "Lo-Fi",
    album: "Café Sessions",
    waveform: generateWaveform("mix-4"),
  },
  {
    id: "mix-5",
    title: "Starlight",
    artist: "Cosmos",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3"),
    cover: COVERS[5],
    genre: "Space",
    album: "Galaxy",
    waveform: generateWaveform("mix-5"),
  },
  {
    id: "mix-6",
    title: "Forest Rain",
    artist: "Nature Sounds",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3"),
    cover: COVERS[6],
    genre: "Nature",
    album: "Forest",
    waveform: generateWaveform("mix-6"),
  },
  {
    id: "mix-7",
    title: "City Lights",
    artist: "Urban Vibes",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3"),
    cover: COVERS[7],
    genre: "Electronic",
    album: "Urban",
    waveform: generateWaveform("mix-7"),
  },
  {
    id: "mix-8",
    title: "Mountain Peak",
    artist: "Adventure",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3"),
    cover: COVERS[8],
    genre: "Epic",
    album: "Mountains",
    waveform: generateWaveform("mix-8"),
  },
  {
    id: "mix-9",
    title: "Tropical Paradise",
    artist: "Island Vibes",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3"),
    cover: COVERS[9],
    genre: "Tropical",
    album: "Beach",
    waveform: generateWaveform("mix-9"),
  },
  {
    id: "mix-10",
    title: "Winter Wonderland",
    artist: "Seasons",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3"),
    cover: COVERS[10],
    genre: "Ambient",
    album: "Seasons",
    waveform: generateWaveform("mix-10"),
  },
  {
    id: "mix-11",
    title: "Rainy Day",
    artist: "Weather Moods",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3"),
    cover: COVERS[11],
    genre: "Chill",
    album: "Weather",
    waveform: generateWaveform("mix-11"),
  },
  {
    id: "mix-12",
    title: "Desert Sun",
    artist: "Horizon",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3"),
    cover: COVERS[12],
    genre: "World",
    album: "Desert",
    waveform: generateWaveform("mix-12"),
  },
  {
    id: "mix-13",
    title: "Northern Lights",
    artist: "Arctic Dreams",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3"),
    cover: COVERS[13],
    genre: "Ambient",
    album: "Arctic",
    waveform: generateWaveform("mix-13"),
  },
  {
    id: "mix-14",
    title: "Zen Garden",
    artist: "Meditation",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3"),
    cover: COVERS[14],
    genre: "Meditation",
    album: "Zen",
    waveform: generateWaveform("mix-14"),
  },
  {
    id: "mix-15",
    title: "Autumn Leaves",
    artist: "Seasons",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3"),
    cover: COVERS[0],
    genre: "Acoustic",
    album: "Seasons",
    waveform: generateWaveform("mix-15"),
  },
  {
    id: "mix-16",
    title: "Spring Awakening",
    artist: "Seasons",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3"),
    cover: COVERS[1],
    genre: "Orchestral",
    album: "Seasons",
    waveform: generateWaveform("mix-16"),
  },
  {
    id: "mix-17",
    title: "Neon Dreams",
    artist: "Cyber Wave",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"),
    cover: COVERS[2],
    genre: "Synthwave",
    album: "Cyberpunk",
    waveform: generateWaveform("mix-17"),
  },
  {
    id: "mix-18",
    title: "Space Station",
    artist: "Cosmos",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3"),
    cover: COVERS[3],
    genre: "Space",
    album: "Galaxy",
    waveform: generateWaveform("mix-18"),
  },
  {
    id: "mix-19",
    title: "Deep Ocean",
    artist: "Aqua Sounds",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3"),
    cover: COVERS[4],
    genre: "Ambient",
    album: "Ocean",
    waveform: generateWaveform("mix-19"),
  },
  {
    id: "mix-20",
    title: "Fireplace",
    artist: "Cozy Vibes",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3"),
    cover: COVERS[5],
    genre: "Ambient",
    album: "Cozy",
    waveform: generateWaveform("mix-20"),
  },
  {
    id: "mix-21",
    title: "Morning Coffee",
    artist: "Café Beats",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3"),
    cover: COVERS[6],
    genre: "Lo-Fi",
    album: "Morning",
    waveform: generateWaveform("mix-21"),
  },
  {
    id: "mix-22",
    title: "Nightclub",
    artist: "Party Mix",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3"),
    cover: COVERS[7],
    genre: "Dance",
    album: "Party",
    waveform: generateWaveform("mix-22"),
  },
  {
    id: "mix-23",
    title: "Road Trip",
    artist: "Highway",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3"),
    cover: COVERS[8],
    genre: "Rock",
    album: "Road",
    waveform: generateWaveform("mix-23"),
  },
  {
    id: "mix-24",
    title: "Moonlight",
    artist: "Night Sky",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3"),
    cover: COVERS[9],
    genre: "Ambient",
    album: "Night",
    waveform: generateWaveform("mix-24"),
  },
  {
    id: "mix-25",
    title: "Sunrise",
    artist: "Dawn",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3"),
    cover: COVERS[10],
    genre: "Chill",
    album: "Morning",
    waveform: generateWaveform("mix-25"),
  },
  {
    id: "mix-26",
    title: "Thunderstorm",
    artist: "Weather Moods",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3"),
    cover: COVERS[11],
    genre: "Ambient",
    album: "Weather",
    waveform: generateWaveform("mix-26"),
  },
  {
    id: "mix-27",
    title: "Waterfall",
    artist: "Nature Sounds",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3"),
    cover: COVERS[12],
    genre: "Nature",
    album: "Water",
    waveform: generateWaveform("mix-27"),
  },
  {
    id: "mix-28",
    title: "Galaxy Explorer",
    artist: "Cosmos",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3"),
    cover: COVERS[13],
    genre: "Space",
    album: "Galaxy",
    waveform: generateWaveform("mix-28"),
  },
  {
    id: "mix-29",
    title: "Piano Dreams",
    artist: "Classical",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3"),
    cover: COVERS[14],
    genre: "Classical",
    album: "Piano",
    waveform: generateWaveform("mix-29"),
  },
  {
    id: "mix-30",
    title: "Guitar Solo",
    artist: "Rock Star",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3"),
    cover: COVERS[0],
    genre: "Rock",
    album: "Guitar",
    waveform: generateWaveform("mix-30"),
  },
  {
    id: "mix-31",
    title: "Violin Concerto",
    artist: "Orchestra",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3"),
    cover: COVERS[1],
    genre: "Classical",
    album: "Orchestra",
    waveform: generateWaveform("mix-31"),
  },
  {
    id: "mix-32",
    title: "Saxophone Blues",
    artist: "Jazz Club",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3"),
    cover: COVERS[2],
    genre: "Jazz",
    album: "Blues",
    waveform: generateWaveform("mix-32"),
  },
  {
    id: "mix-33",
    title: "Drum Circle",
    artist: "Percussion",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"),
    cover: COVERS[3],
    genre: "World",
    album: "Drums",
    waveform: generateWaveform("mix-33"),
  },
  {
    id: "mix-34",
    title: "Flute Melody",
    artist: "Wind Instruments",
    src: proxyUrl("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3"),
    cover: COVERS[4],
    genre: "World",
    album: "Wind",
    waveform: generateWaveform("mix-34"),
  },
];
